name: desuungapp
description: "This is a Mobile application for Desuung."

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  dio: ^5.8.0+1 # For api request
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/communityService.jpeg
    - assets/festival.jpeg
    - assets/health.jpeg
    - assets/leadership.jpeg
    - assets/tech.jpeg


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"